// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVn7BrOBKnX1cIcoE_n_l5-XAwh87WME',
    appId: '1:387293576772:web:d410165bbcd878bc568611',
    messagingSenderId: '387293576772',
    projectId: 'todolistapp-eart',
    authDomain: 'todolistapp-eart.firebaseapp.com',
    storageBucket: 'todolistapp-eart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYB4kKgHux5Bb0epI5lu4VLuStYKgcfpQ',
    appId: '1:387293576772:android:c049850f4a40b566568611',
    messagingSenderId: '387293576772',
    projectId: 'todolistapp-eart',
    storageBucket: 'todolistapp-eart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSrKSmclIhsh1TlHE6peVoHusLDmlgdNQ',
    appId: '1:387293576772:ios:2cde169413acf0a7568611',
    messagingSenderId: '387293576772',
    projectId: 'todolistapp-eart',
    storageBucket: 'todolistapp-eart.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSrKSmclIhsh1TlHE6peVoHusLDmlgdNQ',
    appId: '1:387293576772:ios:2cde169413acf0a7568611',
    messagingSenderId: '387293576772',
    projectId: 'todolistapp-eart',
    storageBucket: 'todolistapp-eart.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzVn7BrOBKnX1cIcoE_n_l5-XAwh87WME',
    appId: '1:387293576772:web:400ecee6f22ff048568611',
    messagingSenderId: '387293576772',
    projectId: 'todolistapp-eart',
    authDomain: 'todolistapp-eart.firebaseapp.com',
    storageBucket: 'todolistapp-eart.appspot.com',
  );
}
